// modules/account-validation/domain/steps.ts

export const Steps = {
  S1_VALIDATE_IBAN: "S1_VALIDATE_IBAN",
  S2_CHECK_ERRORS: "S2_CHECK_ERRORS",
  S3_COUNTRY_SUPPORTED: "S3_COUNTRY_SUPPORTED",
  S4_VALIDATE_BBAN_BIC: "S4_VALIDATE_BBAN_BIC",
  S5_CHECK_ERRORS: "S5_CHECK_ERRORS",
  S6_TREATABLE_AS_ERRORS: "S6_TREATABLE_AS_ERRORS",
  S7_MANUAL_CONFIRMATION_NEEDED: "S7_MANUAL_CONFIRMATION_NEEDED",
  S8_RECONFIRM_EXTERNAL: "S8_RECONFIRM_EXTERNAL",
  S9_COMPARE_RECONFIRM: "S9_COMPARE_RECONFIRM",
  S10_TRANSPOSED: "S10_TRANSPOSED",
  S11_STORE_TRANSPOSED: "S11_STORE_TRANSPOSED",
  S12_IBAN_NEEDS_FORMING: "S12_IBAN_NEEDS_FORMING",
  S13_FORM_IBAN: "S13_FORM_IBAN",
  S14_PRESENT_DETAILS: "S14_PRESENT_DETAILS",
  S15_USER_ACCEPTANCE: "S15_USER_ACCEPTANCE",
} as const;

export type StepId = (typeof Steps)[keyof typeof Steps];
