openapi: 3.0.3

info:
  title: WebElec Backend API
  version: 1.0.0
  description: >
    API REST du SaaS WebElec pour électriciens belges.

    Authentification :
    Tous les endpoints (sauf /api/auth/*) nécessitent un token JWT :
    Authorization: Bearer <token>

servers:
  - url: http://localhost:8080
    description: Serveur de développement

tags:
  - name: Auth
    description: Authentification et gestion des tokens
  - name: Users
    description: Profil technicien, équipe et habilitations RGIE
  - name: Societes
    description: Gestion des sociétés (multi-tenant)
  - name: Clients
    description: Gestion des clients
  - name: Chantiers
    description: Gestion des chantiers
  - name: Produits
    description: Gestion des produits
  - name: ProduitsAvances
    description: Produits avancés et spécialisés
  - name: Interventions
    description: Gestion des interventions
  - name: Devis
    description: Gestion des devis
  - name: Factures
    description: Gestion des factures
  - name: Navigation
    description: Structure du menu latéral dynamique

paths:
  /api/navigation:
    get:
      tags: [Navigation]
      summary: Générer la navigation dynamique
      description: >
        Retourne le menu latéral dynamique pour l'utilisateur authentifié.
        L'utilisateur est déduit du token JWT.
        La société active correspond à la dernière entrée de societe_selections.
        Les modules retournés respectent les permissions du rôle et les licences actives.
        Les modules RGIE disparaissent si la licence associée est inactive ou expirée.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Navigation filtrée par rôle et licences actives
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NavigationResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT obtenu via /api/auth/login

  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
      description: Identifiant unique

  responses:
    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"

    Unauthorized:
      description: Non authentifié
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"

    Forbidden:
      description: Accès refusé
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"

  schemas:
    ApiError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string

    NavigationResponse:
      type: object
      required: [sections]
      properties:
        sections:
          type: array
          items:
            $ref: "#/components/schemas/NavigationSection"

    NavigationSection:
      type: object
      required: [code, label, items]
      properties:
        code:
          type: string
        label:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/NavigationItem"

    NavigationItem:
      type: object
      required: [code, label, route, icon, active]
      properties:
        code:
          type: string
        label:
          type: string
        route:
          type: string
        icon:
          type: string
        active:
          type: boolean
